
package Ventanas;

import Controlador.ElEjercicio;
import Controlador.ElRepaso;
import static Controlador.ElEjercicio.*;
import static Controlador.ElRepaso.aleatorioJornada1;
import static Controlador.ElRepaso.n1;
import static Controlador.ElRepaso.selecJornadaR;
import static Controlador.ElRepaso.siglas;
import Controlador.ElTemario;
import static Controlador.ElTemario.DevolverUrl;
import Controlador.ElTest;
import java.applet.AudioClip;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Image;
import java.awt.PopupMenu;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author campo
 */
public final class Programa extends javax.swing.JFrame {

    /**
     * Creates new form Portada
     */
    public Programa() {
        initComponents();
        setLocation(350, 250);
        setTitle("OPOSICIONES PARA AH");
        setIconImage(getIconImage());
        estadoInicial();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logo.png"));
        return retValue;
    }
    private void estadoInicial(){
        Labaraja.setVisible(false);
        TemarioConstituc.setVisible(false);
        TemarioDefensor.setVisible(false);
        TemarioEspecif.setVisible(false);
        TemarioEspecif1.setVisible(false);
        TemarioGeneral.setVisible(false);
        TemarioL39.setVisible(false);
        TemarioL40.setVisible(false);
        TemarioLGT.setVisible(false);
        TemarioLGobierno.setVisible(false);
        TemarioLIRPF.setVisible(false);
        TemarioLIVA.setVisible(false);
        TemarioLIgualdad.setVisible(false);
        TemarioLJContencioso.setVisible(false);
        TemarioLRBRLocal.setVisible(false);
        TemarioLTransparencia.setVisible(false);
        TemarioRDDepartamentos.setVisible(false);
        TemarioRDDisciplinario.setVisible(false);
        TemarioRGI.setVisible(false);
        TemarioRGR.setVisible(false);
        TemarioRIRPF.setVisible(false);
        TemarioRGSAN.setVisible(false);
        TemarioRIRPF.setVisible(false);
        TemarioRIVA.setVisible(false);
        TemarioRRVA.setVisible(false);
        TemarioTribunalC.setVisible(false);
        calendario.setVisible(false);
        TemarioRTUE.setVisible(false);
        TemarioTUE.setVisible(false);
        TemarioGeneral2.setVisible(false);
        ayudaTemario.setVisible(false);
        ListaJornada.setVisible(false);
        ListaJornada1.setVisible(false);
        ayudaRepaso.setVisible(false);
        solucionRepaso.setVisible(false);
        ayudaTest.setVisible(false);
        ayudaEjercicios.setVisible(false);
        examenBoton.setVisible(false);
        ListaExamenes.setVisible(false);
        solucionBoton.setVisible(false);
        ListaApartados.setVisible(false);
        testBoton.setVisible(false);
        listaTest.setVisible(false);
    }
    private void sonido() {
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/sonido/clic_sonido.wav"));
        Sound.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana = new javax.swing.JPanel();
        botones = new javax.swing.JPanel();
        Temario = new javax.swing.JButton();
        Repaso = new javax.swing.JButton();
        Tests = new javax.swing.JButton();
        Ejercicios = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        PanelPortada = new javax.swing.JPanel();
        autor = new javax.swing.JLabel();
        portada = new javax.swing.JLabel();
        PanelTemario = new javax.swing.JPanel();
        TemarioEspecif = new javax.swing.JLabel();
        TemarioGeneral2 = new javax.swing.JLabel();
        TemarioEspecif1 = new javax.swing.JLabel();
        TemarioGeneral = new javax.swing.JLabel();
        TemarioLGT = new javax.swing.JButton();
        TemarioRGI = new javax.swing.JButton();
        TemarioRGR = new javax.swing.JButton();
        TemarioRGSAN = new javax.swing.JButton();
        TemarioLIVA = new javax.swing.JButton();
        TemarioRIRPF = new javax.swing.JButton();
        TemarioLIRPF = new javax.swing.JButton();
        TemarioRIVA = new javax.swing.JButton();
        TemarioRRVA = new javax.swing.JButton();
        TemarioRDDepartamentos = new javax.swing.JButton();
        TemarioRDDisciplinario = new javax.swing.JButton();
        TemarioLIgualdad = new javax.swing.JButton();
        TemarioLTransparencia = new javax.swing.JButton();
        TemarioLJContencioso = new javax.swing.JButton();
        TemarioRTUE = new javax.swing.JButton();
        TemarioTUE = new javax.swing.JButton();
        TemarioLRBRLocal = new javax.swing.JButton();
        TemarioLGobierno = new javax.swing.JButton();
        TemarioTribunalC = new javax.swing.JButton();
        TemarioDefensor = new javax.swing.JButton();
        TemarioL40 = new javax.swing.JButton();
        TemarioL39 = new javax.swing.JButton();
        TemarioConstituc = new javax.swing.JButton();
        calendario = new javax.swing.JButton();
        ListaJornada = new javax.swing.JComboBox<>();
        ayudaTemario = new javax.swing.JButton();
        cuaderno = new javax.swing.JLabel();
        PanelRepaso = new javax.swing.JPanel();
        Labaraja = new javax.swing.JButton();
        numeroCarta1 = new javax.swing.JLabel();
        numeroCarta2 = new javax.swing.JLabel();
        tipoCarta = new javax.swing.JLabel();
        textoRepaso5 = new javax.swing.JLabel();
        textoRepaso4 = new javax.swing.JLabel();
        textoRepaso3 = new javax.swing.JLabel();
        textoRepaso2 = new javax.swing.JLabel();
        textoRepaso1 = new javax.swing.JLabel();
        textoRepaso = new javax.swing.JLabel();
        ayudaRepaso = new javax.swing.JButton();
        solucionRepaso = new javax.swing.JButton();
        ListaJornada1 = new javax.swing.JComboBox<>();
        bloc = new javax.swing.JLabel();
        carta = new javax.swing.JLabel();
        tapete = new javax.swing.JLabel();
        PanelTest = new javax.swing.JPanel();
        ayudaTest = new javax.swing.JButton();
        listaTest = new javax.swing.JComboBox<>();
        testBoton = new javax.swing.JButton();
        cuaderno2 = new javax.swing.JLabel();
        PanelEjercicios = new javax.swing.JPanel();
        ayudaEjercicios = new javax.swing.JButton();
        ListaApartados = new javax.swing.JComboBox<>();
        ListaExamenes = new javax.swing.JComboBox<>();
        solucionBoton = new javax.swing.JButton();
        examenBoton = new javax.swing.JButton();
        textoExamen6 = new javax.swing.JLabel();
        textoExamen5 = new javax.swing.JLabel();
        textoExamen4 = new javax.swing.JLabel();
        textoExamen3 = new javax.swing.JLabel();
        textoExamen2 = new javax.swing.JLabel();
        textoExamen1 = new javax.swing.JLabel();
        tituloEjercicio = new javax.swing.JLabel();
        apartadoExamen = new javax.swing.JLabel();
        fechaExamen = new javax.swing.JLabel();
        textoExamen = new javax.swing.JLabel();
        carpeta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        ventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botones.setBackground(new java.awt.Color(51, 51, 51));

        Temario.setBackground(new java.awt.Color(51, 51, 51));
        Temario.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Temario.setForeground(new java.awt.Color(204, 204, 204));
        Temario.setText("Temario");
        Temario.setBorder(null);
        Temario.setBorderPainted(false);
        Temario.setContentAreaFilled(false);
        Temario.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Temario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioActionPerformed(evt);
            }
        });

        Repaso.setBackground(new java.awt.Color(51, 51, 51));
        Repaso.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Repaso.setForeground(new java.awt.Color(204, 204, 204));
        Repaso.setText("Repaso");
        Repaso.setBorder(null);
        Repaso.setBorderPainted(false);
        Repaso.setContentAreaFilled(false);
        Repaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepasoActionPerformed(evt);
            }
        });

        Tests.setBackground(new java.awt.Color(51, 51, 51));
        Tests.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Tests.setForeground(new java.awt.Color(204, 204, 204));
        Tests.setText("Tests");
        Tests.setBorder(null);
        Tests.setBorderPainted(false);
        Tests.setContentAreaFilled(false);
        Tests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestsActionPerformed(evt);
            }
        });

        Ejercicios.setBackground(new java.awt.Color(51, 51, 51));
        Ejercicios.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        Ejercicios.setForeground(new java.awt.Color(204, 204, 204));
        Ejercicios.setText("Ejercicios");
        Ejercicios.setBorder(null);
        Ejercicios.setBorderPainted(false);
        Ejercicios.setContentAreaFilled(false);
        Ejercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjerciciosActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(60, 63, 65));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_X.png"))); // NOI18N
        Salir.setBorder(null);
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Home.setBackground(new java.awt.Color(60, 63, 65));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        Home.setBorder(null);
        Home.setBorderPainted(false);
        Home.setContentAreaFilled(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        version.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        version.setForeground(new java.awt.Color(204, 204, 204));
        version.setText("Version 1.023");

        fecha.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        fecha.setForeground(new java.awt.Color(204, 204, 204));
        fecha.setText("Oct-2022");

        javax.swing.GroupLayout botonesLayout = new javax.swing.GroupLayout(botones);
        botones.setLayout(botonesLayout);
        botonesLayout.setHorizontalGroup(
            botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonesLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(Home)
                .addGap(83, 83, 83)
                .addComponent(Salir)
                .addContainerGap())
            .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Temario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Repaso, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tests, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ejercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(botonesLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(logo)
                                .addGroup(botonesLayout.createSequentialGroup()
                                    .addComponent(fecha)
                                    .addGap(124, 124, 124)
                                    .addComponent(version)))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        botonesLayout.setVerticalGroup(
            botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(581, Short.MAX_VALUE))
            .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(botonesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(126, 126, 126)
                    .addComponent(Temario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(Repaso, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(Tests, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(Ejercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(130, 130, 130)
                    .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fecha)
                        .addComponent(version))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ventana.add(botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 600));

        PanelPortada.setBackground(new java.awt.Color(255, 255, 255));
        PanelPortada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        autor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        autor.setForeground(new java.awt.Color(51, 51, 51));
        autor.setText("Autor: Miguel Ángel Campos Galán");
        PanelPortada.add(autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 350, 80));

        portada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/portada.png"))); // NOI18N
        portada.setText("Version 1.023");
        PanelPortada.add(portada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 600));

        ventana.add(PanelPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 890, 600));

        PanelTemario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TemarioEspecif.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TemarioEspecif.setForeground(new java.awt.Color(102, 102, 102));
        TemarioEspecif.setText("PARA EXAMEN TIPO TEST Y PRÁCTICO");
        PanelTemario.add(TemarioEspecif, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, 30));

        TemarioGeneral2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TemarioGeneral2.setForeground(new java.awt.Color(102, 102, 102));
        TemarioGeneral2.setText("PARA EXAMEN TIPO TEST");
        PanelTemario.add(TemarioGeneral2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 30));

        TemarioEspecif1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        TemarioEspecif1.setForeground(new java.awt.Color(51, 51, 51));
        TemarioEspecif1.setText("PARTE ESPECIFICA (BLOQUE III):");
        PanelTemario.add(TemarioEspecif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 290, 30));

        TemarioGeneral.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        TemarioGeneral.setForeground(new java.awt.Color(0, 0, 0));
        TemarioGeneral.setText("PARTE GENERAL (BLOQUE I y II):");
        PanelTemario.add(TemarioGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 280, 30));

        TemarioLGT.setBackground(new java.awt.Color(51, 51, 51));
        TemarioLGT.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioLGT.setForeground(new java.awt.Color(0, 0, 0));
        TemarioLGT.setText("Ley General Tributaria (LGT).");
        TemarioLGT.setBorder(null);
        TemarioLGT.setBorderPainted(false);
        TemarioLGT.setContentAreaFilled(false);
        TemarioLGT.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioLGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioLGTActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioLGT, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 270, -1));

        TemarioRGI.setBackground(new java.awt.Color(51, 51, 51));
        TemarioRGI.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioRGI.setForeground(new java.awt.Color(0, 0, 0));
        TemarioRGI.setText("Reglamento General (RGI). ");
        TemarioRGI.setBorder(null);
        TemarioRGI.setBorderPainted(false);
        TemarioRGI.setContentAreaFilled(false);
        TemarioRGI.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioRGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioRGIActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioRGI, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 310, 30));

        TemarioRGR.setBackground(new java.awt.Color(51, 51, 51));
        TemarioRGR.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioRGR.setForeground(new java.awt.Color(0, 0, 0));
        TemarioRGR.setText("Reglamento General de Recaudación (RGR).");
        TemarioRGR.setBorder(null);
        TemarioRGR.setBorderPainted(false);
        TemarioRGR.setContentAreaFilled(false);
        TemarioRGR.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioRGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioRGRActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioRGR, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 310, 30));

        TemarioRGSAN.setBackground(new java.awt.Color(51, 51, 51));
        TemarioRGSAN.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioRGSAN.setForeground(new java.awt.Color(0, 0, 0));
        TemarioRGSAN.setText("Reglamento General Sancionador (RGSAN). ");
        TemarioRGSAN.setBorder(null);
        TemarioRGSAN.setBorderPainted(false);
        TemarioRGSAN.setContentAreaFilled(false);
        TemarioRGSAN.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioRGSAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioRGSANActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioRGSAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 310, 30));

        TemarioLIVA.setBackground(new java.awt.Color(51, 51, 51));
        TemarioLIVA.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioLIVA.setForeground(new java.awt.Color(0, 0, 0));
        TemarioLIVA.setText("Ley sobre el Impuesto IVA.");
        TemarioLIVA.setBorder(null);
        TemarioLIVA.setBorderPainted(false);
        TemarioLIVA.setContentAreaFilled(false);
        TemarioLIVA.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioLIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioLIVAActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioLIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 310, 30));

        TemarioRIRPF.setBackground(new java.awt.Color(51, 51, 51));
        TemarioRIRPF.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioRIRPF.setForeground(new java.awt.Color(0, 0, 0));
        TemarioRIRPF.setText("Reglamento sobre el Impuesto IRPF.");
        TemarioRIRPF.setBorder(null);
        TemarioRIRPF.setBorderPainted(false);
        TemarioRIRPF.setContentAreaFilled(false);
        TemarioRIRPF.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioRIRPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioRIRPFActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioRIRPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 310, 30));

        TemarioLIRPF.setBackground(new java.awt.Color(51, 51, 51));
        TemarioLIRPF.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioLIRPF.setForeground(new java.awt.Color(0, 0, 0));
        TemarioLIRPF.setText("Ley sobre el Impuesto IRPF.");
        TemarioLIRPF.setBorder(null);
        TemarioLIRPF.setBorderPainted(false);
        TemarioLIRPF.setContentAreaFilled(false);
        TemarioLIRPF.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioLIRPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioLIRPFActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioLIRPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 310, 30));

        TemarioRIVA.setBackground(new java.awt.Color(51, 51, 51));
        TemarioRIVA.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioRIVA.setForeground(new java.awt.Color(0, 0, 0));
        TemarioRIVA.setText("Reglamento sobre el Impuesto IVA.");
        TemarioRIVA.setBorder(null);
        TemarioRIVA.setBorderPainted(false);
        TemarioRIVA.setContentAreaFilled(false);
        TemarioRIVA.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioRIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioRIVAActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioRIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 310, 30));

        TemarioRRVA.setBackground(new java.awt.Color(51, 51, 51));
        TemarioRRVA.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioRRVA.setForeground(new java.awt.Color(0, 0, 0));
        TemarioRRVA.setText("Reglamento General de Revisión (RRVA). ");
        TemarioRRVA.setBorder(null);
        TemarioRRVA.setBorderPainted(false);
        TemarioRRVA.setContentAreaFilled(false);
        TemarioRRVA.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioRRVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioRRVAActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioRRVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 310, 30));

        TemarioRDDepartamentos.setBackground(new java.awt.Color(51, 51, 51));
        TemarioRDDepartamentos.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioRDDepartamentos.setForeground(new java.awt.Color(0, 0, 0));
        TemarioRDDepartamentos.setText("Departamentos Ministeriales.");
        TemarioRDDepartamentos.setBorder(null);
        TemarioRDDepartamentos.setBorderPainted(false);
        TemarioRDDepartamentos.setContentAreaFilled(false);
        TemarioRDDepartamentos.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioRDDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioRDDepartamentosActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioRDDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 280, 30));

        TemarioRDDisciplinario.setBackground(new java.awt.Color(51, 51, 51));
        TemarioRDDisciplinario.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioRDDisciplinario.setForeground(new java.awt.Color(0, 0, 0));
        TemarioRDDisciplinario.setText("Reg. del Régimen Disciplinario de los Funcionarios.");
        TemarioRDDisciplinario.setBorder(null);
        TemarioRDDisciplinario.setBorderPainted(false);
        TemarioRDDisciplinario.setContentAreaFilled(false);
        TemarioRDDisciplinario.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioRDDisciplinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioRDDisciplinarioActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioRDDisciplinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 380, 20));

        TemarioLIgualdad.setBackground(new java.awt.Color(51, 51, 51));
        TemarioLIgualdad.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioLIgualdad.setForeground(new java.awt.Color(0, 0, 0));
        TemarioLIgualdad.setText("Ley de Igualdad.");
        TemarioLIgualdad.setBorder(null);
        TemarioLIgualdad.setBorderPainted(false);
        TemarioLIgualdad.setContentAreaFilled(false);
        TemarioLIgualdad.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioLIgualdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioLIgualdadActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioLIgualdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 320, -1));

        TemarioLTransparencia.setBackground(new java.awt.Color(51, 51, 51));
        TemarioLTransparencia.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioLTransparencia.setForeground(new java.awt.Color(0, 0, 0));
        TemarioLTransparencia.setText("Ley de Transparencia.");
        TemarioLTransparencia.setBorder(null);
        TemarioLTransparencia.setBorderPainted(false);
        TemarioLTransparencia.setContentAreaFilled(false);
        TemarioLTransparencia.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioLTransparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioLTransparenciaActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioLTransparencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 401, 320, 30));

        TemarioLJContencioso.setBackground(new java.awt.Color(51, 51, 51));
        TemarioLJContencioso.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioLJContencioso.setForeground(new java.awt.Color(0, 0, 0));
        TemarioLJContencioso.setText("Ley de la Jurisdicción Contencioso-administrativa.");
        TemarioLJContencioso.setBorder(null);
        TemarioLJContencioso.setBorderPainted(false);
        TemarioLJContencioso.setContentAreaFilled(false);
        TemarioLJContencioso.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioLJContencioso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioLJContenciosoActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioLJContencioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 320, -1));

        TemarioRTUE.setBackground(new java.awt.Color(51, 51, 51));
        TemarioRTUE.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioRTUE.setForeground(new java.awt.Color(0, 0, 0));
        TemarioRTUE.setText("Reglamento Tratado de la Unión Europea.");
        TemarioRTUE.setBorder(null);
        TemarioRTUE.setBorderPainted(false);
        TemarioRTUE.setContentAreaFilled(false);
        TemarioRTUE.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioRTUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioRTUEActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioRTUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 320, -1));

        TemarioTUE.setBackground(new java.awt.Color(51, 51, 51));
        TemarioTUE.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioTUE.setForeground(new java.awt.Color(0, 0, 0));
        TemarioTUE.setText("Tratado de la Unión Europea.");
        TemarioTUE.setBorder(null);
        TemarioTUE.setBorderPainted(false);
        TemarioTUE.setContentAreaFilled(false);
        TemarioTUE.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioTUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioTUEActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioTUE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 320, -1));

        TemarioLRBRLocal.setBackground(new java.awt.Color(51, 51, 51));
        TemarioLRBRLocal.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioLRBRLocal.setForeground(new java.awt.Color(0, 0, 0));
        TemarioLRBRLocal.setText("Ley Reguladora del Regimen Local.");
        TemarioLRBRLocal.setBorder(null);
        TemarioLRBRLocal.setBorderPainted(false);
        TemarioLRBRLocal.setContentAreaFilled(false);
        TemarioLRBRLocal.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioLRBRLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioLRBRLocalActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioLRBRLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 320, 30));

        TemarioLGobierno.setBackground(new java.awt.Color(51, 51, 51));
        TemarioLGobierno.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioLGobierno.setForeground(new java.awt.Color(0, 0, 0));
        TemarioLGobierno.setText("Ley del Gobierno.");
        TemarioLGobierno.setBorder(null);
        TemarioLGobierno.setBorderPainted(false);
        TemarioLGobierno.setContentAreaFilled(false);
        TemarioLGobierno.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioLGobierno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioLGobiernoActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioLGobierno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 320, 20));

        TemarioTribunalC.setBackground(new java.awt.Color(51, 51, 51));
        TemarioTribunalC.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioTribunalC.setForeground(new java.awt.Color(0, 0, 0));
        TemarioTribunalC.setText("Tribunal Constitucional.");
        TemarioTribunalC.setBorder(null);
        TemarioTribunalC.setBorderPainted(false);
        TemarioTribunalC.setContentAreaFilled(false);
        TemarioTribunalC.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioTribunalC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioTribunalCActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioTribunalC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 320, -1));

        TemarioDefensor.setBackground(new java.awt.Color(51, 51, 51));
        TemarioDefensor.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioDefensor.setForeground(new java.awt.Color(0, 0, 0));
        TemarioDefensor.setText("Defensor del Pueblo.");
        TemarioDefensor.setBorder(null);
        TemarioDefensor.setBorderPainted(false);
        TemarioDefensor.setContentAreaFilled(false);
        TemarioDefensor.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioDefensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioDefensorActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioDefensor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 320, 30));

        TemarioL40.setBackground(new java.awt.Color(51, 51, 51));
        TemarioL40.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioL40.setForeground(new java.awt.Color(0, 0, 0));
        TemarioL40.setText("Ley de Régimen Jurídico del Sector Público.");
        TemarioL40.setBorder(null);
        TemarioL40.setBorderPainted(false);
        TemarioL40.setContentAreaFilled(false);
        TemarioL40.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioL40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioL40ActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioL40, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 320, -1));

        TemarioL39.setBackground(new java.awt.Color(51, 51, 51));
        TemarioL39.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioL39.setForeground(new java.awt.Color(0, 0, 0));
        TemarioL39.setText("Ley del Procedimiento Administrativo Común.");
        TemarioL39.setBorder(null);
        TemarioL39.setBorderPainted(false);
        TemarioL39.setContentAreaFilled(false);
        TemarioL39.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioL39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioL39ActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioL39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 320, 30));

        TemarioConstituc.setBackground(new java.awt.Color(51, 51, 51));
        TemarioConstituc.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        TemarioConstituc.setForeground(new java.awt.Color(0, 0, 0));
        TemarioConstituc.setText("Constitución Española.");
        TemarioConstituc.setBorder(null);
        TemarioConstituc.setBorderPainted(false);
        TemarioConstituc.setContentAreaFilled(false);
        TemarioConstituc.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        TemarioConstituc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemarioConstitucActionPerformed(evt);
            }
        });
        PanelTemario.add(TemarioConstituc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 270, -1));

        calendario.setBackground(new java.awt.Color(102, 0, 0));
        calendario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calendario.setForeground(new java.awt.Color(153, 153, 153));
        calendario.setText("Jornada de estudio");
        calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioActionPerformed(evt);
            }
        });
        PanelTemario.add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, -1, -1));

        ListaJornada.setBackground(new java.awt.Color(204, 204, 204));
        ListaJornada.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ListaJornada.setForeground(new java.awt.Color(102, 102, 102));
        ListaJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Primera Jornada", "Segunda Jornada", "Tercera Jornada" }));
        ListaJornada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListaJornadaItemStateChanged(evt);
            }
        });
        ListaJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaJornadaActionPerformed(evt);
            }
        });
        PanelTemario.add(ListaJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        ayudaTemario.setBackground(new java.awt.Color(51, 51, 51));
        ayudaTemario.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        ayudaTemario.setForeground(new java.awt.Color(0, 0, 0));
        ayudaTemario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda.png"))); // NOI18N
        ayudaTemario.setBorder(null);
        ayudaTemario.setBorderPainted(false);
        ayudaTemario.setContentAreaFilled(false);
        ayudaTemario.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        ayudaTemario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaTemarioActionPerformed(evt);
            }
        });
        PanelTemario.add(ayudaTemario, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 160, 170));

        cuaderno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuaderno.png"))); // NOI18N
        cuaderno.setText("jLabel1");
        PanelTemario.add(cuaderno, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 910, 600));

        ventana.add(PanelTemario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 890, 600));

        PanelRepaso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Labaraja.setBackground(new java.awt.Color(60, 63, 65));
        Labaraja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baraja.png"))); // NOI18N
        Labaraja.setBorder(null);
        Labaraja.setBorderPainted(false);
        Labaraja.setContentAreaFilled(false);
        Labaraja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabarajaActionPerformed(evt);
            }
        });
        PanelRepaso.add(Labaraja, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 220, 310));

        numeroCarta1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        numeroCarta1.setForeground(new java.awt.Color(0, 0, 0));
        PanelRepaso.add(numeroCarta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 40, 30));

        numeroCarta2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        numeroCarta2.setForeground(new java.awt.Color(0, 0, 0));
        PanelRepaso.add(numeroCarta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 40, 30));

        tipoCarta.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        tipoCarta.setForeground(new java.awt.Color(0, 0, 0));
        PanelRepaso.add(tipoCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 100, 70));

        textoRepaso5.setForeground(new java.awt.Color(0, 0, 0));
        textoRepaso5.setText("Selecciona la jornada.");
        PanelRepaso.add(textoRepaso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 190, 30));

        textoRepaso4.setForeground(new java.awt.Color(0, 0, 0));
        textoRepaso4.setText("abajo que pone solución.");
        PanelRepaso.add(textoRepaso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 190, 30));

        textoRepaso3.setForeground(new java.awt.Color(0, 0, 0));
        textoRepaso3.setText("acertado pulsa el botón de");
        PanelRepaso.add(textoRepaso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 190, 30));

        textoRepaso2.setForeground(new java.awt.Color(0, 0, 0));
        textoRepaso2.setText("es.  Luego, para saber si has");
        PanelRepaso.add(textoRepaso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 190, 30));

        textoRepaso1.setForeground(new java.awt.Color(0, 0, 0));
        textoRepaso1.setText("intenta recordar que artículo");
        PanelRepaso.add(textoRepaso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 190, 30));

        textoRepaso.setForeground(new java.awt.Color(0, 0, 0));
        textoRepaso.setText("Pulsa en la baraja, luego");
        PanelRepaso.add(textoRepaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 190, 30));

        ayudaRepaso.setBackground(new java.awt.Color(60, 63, 65));
        ayudaRepaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda.png"))); // NOI18N
        ayudaRepaso.setBorder(null);
        ayudaRepaso.setBorderPainted(false);
        ayudaRepaso.setContentAreaFilled(false);
        ayudaRepaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaRepasoActionPerformed(evt);
            }
        });
        PanelRepaso.add(ayudaRepaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 210, 150));

        solucionRepaso.setBackground(new java.awt.Color(204, 0, 0));
        solucionRepaso.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        solucionRepaso.setForeground(new java.awt.Color(255, 255, 255));
        solucionRepaso.setText("Solución");
        solucionRepaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solucionRepasoActionPerformed(evt);
            }
        });
        PanelRepaso.add(solucionRepaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, -1));

        ListaJornada1.setBackground(new java.awt.Color(204, 204, 204));
        ListaJornada1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ListaJornada1.setForeground(new java.awt.Color(102, 102, 102));
        ListaJornada1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Primera Jornada", "Segunda Jornada", "Tercera Jornada" }));
        ListaJornada1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListaJornada1ItemStateChanged(evt);
            }
        });
        ListaJornada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaJornada1ActionPerformed(evt);
            }
        });
        PanelRepaso.add(ListaJornada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        bloc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notas_boli.png"))); // NOI18N
        PanelRepaso.add(bloc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, -180, 360, 790));
        PanelRepaso.add(carta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 210, 310));

        tapete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tapete.png"))); // NOI18N
        tapete.setText("jLabel1");
        PanelRepaso.add(tapete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        ventana.add(PanelRepaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 890, 600));

        PanelTest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ayudaTest.setBackground(new java.awt.Color(51, 51, 51));
        ayudaTest.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        ayudaTest.setForeground(new java.awt.Color(0, 0, 0));
        ayudaTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda.png"))); // NOI18N
        ayudaTest.setBorder(null);
        ayudaTest.setBorderPainted(false);
        ayudaTest.setContentAreaFilled(false);
        ayudaTest.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        ayudaTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaTestActionPerformed(evt);
            }
        });
        PanelTest.add(ayudaTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 160, 170));

        listaTest.setBackground(new java.awt.Color(204, 204, 204));
        listaTest.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        listaTest.setForeground(new java.awt.Color(102, 102, 102));
        listaTest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "2020" }));
        listaTest.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaTestItemStateChanged(evt);
            }
        });
        listaTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaTestActionPerformed(evt);
            }
        });
        PanelTest.add(listaTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        testBoton.setBackground(new java.awt.Color(102, 0, 0));
        testBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        testBoton.setForeground(new java.awt.Color(153, 153, 153));
        testBoton.setText("Hacer examen");
        testBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testBotonActionPerformed(evt);
            }
        });
        PanelTest.add(testBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        cuaderno2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuaderno.png"))); // NOI18N
        cuaderno2.setText("jLabel1");
        PanelTest.add(cuaderno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 900, 600));

        ventana.add(PanelTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 890, 600));

        PanelEjercicios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ayudaEjercicios.setBackground(new java.awt.Color(51, 51, 51));
        ayudaEjercicios.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        ayudaEjercicios.setForeground(new java.awt.Color(0, 0, 0));
        ayudaEjercicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda.png"))); // NOI18N
        ayudaEjercicios.setBorder(null);
        ayudaEjercicios.setBorderPainted(false);
        ayudaEjercicios.setContentAreaFilled(false);
        ayudaEjercicios.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        ayudaEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaEjerciciosActionPerformed(evt);
            }
        });
        PanelEjercicios.add(ayudaEjercicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 160, 170));

        ListaApartados.setBackground(new java.awt.Color(204, 204, 204));
        ListaApartados.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ListaApartados.setForeground(new java.awt.Color(102, 102, 102));
        ListaApartados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "2020_ap_1" }));
        ListaApartados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListaApartadosItemStateChanged(evt);
            }
        });
        ListaApartados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaApartadosActionPerformed(evt);
            }
        });
        PanelEjercicios.add(ListaApartados, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        ListaExamenes.setBackground(new java.awt.Color(204, 204, 204));
        ListaExamenes.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ListaExamenes.setForeground(new java.awt.Color(102, 102, 102));
        ListaExamenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "2020" }));
        ListaExamenes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ListaExamenesItemStateChanged(evt);
            }
        });
        ListaExamenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaExamenesActionPerformed(evt);
            }
        });
        PanelEjercicios.add(ListaExamenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));

        solucionBoton.setBackground(new java.awt.Color(102, 0, 0));
        solucionBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        solucionBoton.setForeground(new java.awt.Color(153, 153, 153));
        solucionBoton.setText("Solución del apartado");
        solucionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solucionBotonActionPerformed(evt);
            }
        });
        PanelEjercicios.add(solucionBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, -1));

        examenBoton.setBackground(new java.awt.Color(102, 0, 0));
        examenBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        examenBoton.setForeground(new java.awt.Color(153, 153, 153));
        examenBoton.setText("Hacer examen");
        examenBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examenBotonActionPerformed(evt);
            }
        });
        PanelEjercicios.add(examenBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, -1, -1));

        textoExamen6.setForeground(new java.awt.Color(0, 0, 0));
        textoExamen6.setText("propongo).");
        PanelEjercicios.add(textoExamen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 340, 30));

        textoExamen5.setForeground(new java.awt.Color(0, 0, 0));
        textoExamen5.setText("(La solución no es oficial, es una solución que yo ");
        PanelEjercicios.add(textoExamen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 340, 30));

        textoExamen4.setForeground(new java.awt.Color(0, 0, 0));
        textoExamen4.setText("el botón 'Solución del apartado'.");
        PanelEjercicios.add(textoExamen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 30));

        textoExamen3.setForeground(new java.awt.Color(0, 0, 0));
        textoExamen3.setText("apartado, elige dicho apartado y luego pulsa el");
        PanelEjercicios.add(textoExamen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, 30));

        textoExamen2.setForeground(new java.awt.Color(0, 0, 0));
        textoExamen2.setText("examen'. Luego si quieres ver la solución de cada ");
        PanelEjercicios.add(textoExamen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 30));

        textoExamen1.setForeground(new java.awt.Color(0, 0, 0));
        textoExamen1.setText("que quieres realizar y pulsa el botón 'Hacer   ");
        PanelEjercicios.add(textoExamen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 310, 30));

        tituloEjercicio.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tituloEjercicio.setForeground(new java.awt.Color(0, 0, 0));
        tituloEjercicio.setText("EJERCICIOS:");
        PanelEjercicios.add(tituloEjercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 280, 30));

        apartadoExamen.setForeground(new java.awt.Color(0, 0, 0));
        apartadoExamen.setText("Elige apartado:");
        PanelEjercicios.add(apartadoExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        fechaExamen.setForeground(new java.awt.Color(0, 0, 0));
        fechaExamen.setText("Elige examen:");
        PanelEjercicios.add(fechaExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        textoExamen.setForeground(new java.awt.Color(0, 0, 0));
        textoExamen.setText("En este apartado tienes que elegir  el examen");
        PanelEjercicios.add(textoExamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 310, 30));

        carpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuaderno.png"))); // NOI18N
        carpeta.setText("jLabel1");
        PanelEjercicios.add(carpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 900, 600));

        ventana.add(PanelEjercicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 890, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ventana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void TemarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioActionPerformed
        sonido();
        PanelPortada.setVisible(false);
        PanelEjercicios.setVisible(false);
        PanelTest.setVisible(false);
        PanelRepaso.setVisible(false);
        PanelTemario.setVisible(true);
        TemarioConstituc.setVisible(true);
        TemarioDefensor.setVisible(true);
        TemarioEspecif.setVisible(true);
        TemarioEspecif1.setVisible(true);
        TemarioGeneral.setVisible(true);
        TemarioL39.setVisible(true);
        TemarioL40.setVisible(true);
        TemarioLGT.setVisible(true);
        TemarioLGobierno.setVisible(true);
        TemarioLIRPF.setVisible(true);
        TemarioLIVA.setVisible(true);
        TemarioLIgualdad.setVisible(true);
        TemarioLJContencioso.setVisible(true);
        TemarioLRBRLocal.setVisible(true);
        TemarioLTransparencia.setVisible(true);
        TemarioRDDepartamentos.setVisible(true);
        TemarioRDDisciplinario.setVisible(true);
        TemarioRGI.setVisible(true);
        TemarioRGR.setVisible(true);
        TemarioRIRPF.setVisible(true);
        TemarioRGSAN.setVisible(true);
        TemarioRIRPF.setVisible(true);
        TemarioRIVA.setVisible(true);
        TemarioRRVA.setVisible(true);
        TemarioTribunalC.setVisible(true);
        calendario.setVisible(true);
        TemarioRTUE.setVisible(true);
        TemarioTUE.setVisible(true);
        TemarioGeneral2.setVisible(true);
        ayudaTemario.setVisible(true);
        ListaJornada.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed

        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void RepasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepasoActionPerformed
        sonido();
        PanelPortada.setVisible(false);
        PanelTemario.setVisible(false);
        PanelEjercicios.setVisible(false);
        PanelTest.setVisible(false);
        PanelRepaso.setVisible(true);
        Labaraja.setVisible(true);
        ListaJornada1.setVisible(true);
        ayudaRepaso.setVisible(true);
        solucionRepaso.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_RepasoActionPerformed

    private void TestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestsActionPerformed
        sonido();
        PanelPortada.setVisible(false);
        PanelTemario.setVisible(false);
        PanelRepaso.setVisible(false);
        PanelEjercicios.setVisible(false);
        PanelTest.setVisible(true);
        ayudaTest.setVisible(true);
        testBoton.setVisible(true);
        listaTest.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_TestsActionPerformed

    private void EjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjerciciosActionPerformed
        sonido();
        PanelPortada.setVisible(false);
        PanelTemario.setVisible(false);
        PanelRepaso.setVisible(false);
        PanelTest.setVisible(false);
        PanelEjercicios.setVisible(true);
        ayudaEjercicios.setVisible(true);
        examenBoton.setVisible(true);
        ListaExamenes.setVisible(true);
        solucionBoton.setVisible(true);
        
        ListaApartados.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_EjerciciosActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        sonido();
        PanelTemario.setVisible(false);
        PanelRepaso.setVisible(false);
        PanelTest.setVisible(false);
        PanelEjercicios.setVisible(false);
        PanelPortada.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_HomeActionPerformed

    private void LabarajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabarajaActionPerformed
        sonido();
        try{
         carta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carta1.png")));
         if(selecJornadaR.equals("Primera Jornada"))
            aleatorioJornada1();
        else if(selecJornadaR.equals("Segunda Jornada")){
            aleatorioJornada1();
        }else if(selecJornadaR.equals("Seleccionar")){
             n1="?";
             siglas="????";
        }else{
            aleatorioJornada1();
        }
        }catch(Exception e){
        carta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/joker1.png")));
        
        
    }
       
        //if(null==siglas)tipoCarta.setForeground(new java.awt.Color(102, 102, 102));
        switch (siglas) {
            case "LGT":
                tipoCarta.setForeground(new java.awt.Color(255, 0, 0));
                break;
            case "CE":
                tipoCarta.setForeground(new java.awt.Color(0, 0, 255));
                break;
            default:
                tipoCarta.setForeground(new java.awt.Color(102, 102, 102));
                break;
        }
        tipoCarta.setText(siglas);
        numeroCarta1.setText(n1);
        numeroCarta2.setText(n1);

        // TODO add your handling code here:
    }//GEN-LAST:event_LabarajaActionPerformed

    private void TemarioLGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioLGTActionPerformed
        String urlLGT = "https://www.boe.es/buscar/act.php?id=BOE-A-2003-23186";;
        try {
            DevolverUrl(urlLGT);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TemarioLGTActionPerformed

    private void TemarioRGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioRGIActionPerformed
        String urlRGI = "https://www.boe.es/buscar/act.php?id=BOE-A-2007-15984";
        try {
            DevolverUrl(urlRGI);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioRGIActionPerformed

    private void TemarioRGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioRGRActionPerformed
        String urlRGR = "https://www.boe.es/buscar/act.php?id=BOE-A-2005-14803";
        try {
            DevolverUrl(urlRGR);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_TemarioRGRActionPerformed

    private void TemarioRGSANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioRGSANActionPerformed
        String urlRGSAN = "https://www.boe.es/buscar/act.php?id=BOE-A-2004-18398";
        try {
            DevolverUrl(urlRGSAN);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioRGSANActionPerformed

    private void TemarioRRVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioRRVAActionPerformed
        String urlRRVA = "https://www.boe.es/buscar/act.php?id=BOE-A-2005-8662";
        try {
            DevolverUrl(urlRRVA);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_TemarioRRVAActionPerformed

    private void TemarioLIRPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioLIRPFActionPerformed
        String urlLIRPF = "https://www.boe.es/buscar/act.php?id=BOE-A-2006-20764";
        try {
            DevolverUrl(urlLIRPF);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioLIRPFActionPerformed

    private void TemarioRIRPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioRIRPFActionPerformed
        String urlRIRPF = "https://www.boe.es/buscar/act.php?id=BOE-A-2007-6820";
        try {
            DevolverUrl(urlRIRPF);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioRIRPFActionPerformed

    private void TemarioLIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioLIVAActionPerformed
        String urlLIVA = "https://www.boe.es/buscar/act.php?id=BOE-A-1992-28740";
        try {
            DevolverUrl(urlLIVA);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioLIVAActionPerformed

    private void TemarioRIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioRIVAActionPerformed
        String urlRIVA = "https://www.boe.es/buscar/act.php?id=BOE-A-1992-28925";
        try {
            DevolverUrl(urlRIVA);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioRIVAActionPerformed

    private void TemarioConstitucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioConstitucActionPerformed
    String urlConstituc = "https://www.boe.es/buscar/act.php?id=BOE-A-1978-31229";
        try {
            DevolverUrl(urlConstituc);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }    

    // TODO add your handling code here:
    }//GEN-LAST:event_TemarioConstitucActionPerformed

    private void TemarioL39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioL39ActionPerformed
        String urlL39="https://www.boe.es/buscar/act.php?id=BOE-A-2015-10565";
        try {
            DevolverUrl(urlL39);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioL39ActionPerformed

    private void TemarioL40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioL40ActionPerformed
       String urlL40="https://www.boe.es/buscar/act.php?id=BOE-A-2015-10566";
        try {
            DevolverUrl(urlL40);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioL40ActionPerformed

    private void calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioActionPerformed
        sonido();
        
        JOptionPane.showMessageDialog(null,ElTemario.jornada,
                    "Jornada de estudio", JOptionPane.PLAIN_MESSAGE);
        
        
    // TODO add your handling code here:
    }//GEN-LAST:event_calendarioActionPerformed

    private void TemarioDefensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioDefensorActionPerformed
        String urlDefensor="https://www.boe.es/buscar/act.php?id=BOE-A-1981-10325";
        try {
            DevolverUrl(urlDefensor);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioDefensorActionPerformed

    private void TemarioTribunalCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioTribunalCActionPerformed
        String urlTribunal="https://www.boe.es/buscar/act.php?id=BOE-A-1979-23709";
        try {
            DevolverUrl(urlTribunal);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
// TODO add your handling code here:
    }//GEN-LAST:event_TemarioTribunalCActionPerformed

    private void TemarioLGobiernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioLGobiernoActionPerformed
        String urlLGobierno="https://www.boe.es/buscar/act.php?id=BOE-A-1997-25336";
        try {
            DevolverUrl(urlLGobierno);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_TemarioLGobiernoActionPerformed

    private void TemarioLRBRLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioLRBRLocalActionPerformed
      String urlLRLocal="https://www.boe.es/buscar/act.php?id=BOE-A-1985-5392";
        try {
            DevolverUrl(urlLRLocal);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_TemarioLRBRLocalActionPerformed

    private void TemarioTUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioTUEActionPerformed
        String urlTUE="https://www.boe.es/doue/2010/083/Z00013-00046.pdf";
        try {
            DevolverUrl(urlTUE);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_TemarioTUEActionPerformed

    private void TemarioRTUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioRTUEActionPerformed
        String urlRTUE="https://www.boe.es/doue/2021/057/L00017-00075.pdf";
        try {
            DevolverUrl(urlRTUE);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TemarioRTUEActionPerformed

    private void TemarioLJContenciosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioLJContenciosoActionPerformed
       String urlLContAd="https://www.boe.es/buscar/act.php?id=BOE-A-1998-16718";
        try {
            DevolverUrl(urlLContAd);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TemarioLJContenciosoActionPerformed

    private void TemarioLTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioLTransparenciaActionPerformed
        String urlLTranspa="https://www.boe.es/buscar/act.php?id=BOE-A-2013-12887";
        try {
            DevolverUrl(urlLTranspa);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TemarioLTransparenciaActionPerformed

    private void TemarioLIgualdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioLIgualdadActionPerformed
        String urlLIgualdad="https://www.boe.es/buscar/act.php?id=BOE-A-2007-6115";
        try {
            DevolverUrl(urlLIgualdad);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TemarioLIgualdadActionPerformed

    private void TemarioRDDisciplinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioRDDisciplinarioActionPerformed
        String urlDisciplinario="https://www.boe.es/buscar/act.php?id=BOE-A-1986-1216";
        try {
            DevolverUrl(urlDisciplinario);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TemarioRDDisciplinarioActionPerformed

    private void TemarioRDDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemarioRDDepartamentosActionPerformed
        String urlDepartamentos="https://www.boe.es/buscar/act.php?id=BOE-A-2020-410";
        try {
            DevolverUrl(urlDepartamentos);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Programa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TemarioRDDepartamentosActionPerformed

    private void ListaJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaJornadaActionPerformed
    
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaJornadaActionPerformed

    private void ListaJornadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListaJornadaItemStateChanged
        
        Object selecJornada= ListaJornada.getSelectedItem();
        if(selecJornada.equals("Primera Jornada"))
            ElTemario.jornada=ElTemario.jornada1;
        else if(selecJornada.equals("Segunda Jornada")){
            ElTemario.jornada=ElTemario.jornada2;
        }else if(selecJornada.equals("Tercera Jornada")){
            ElTemario.jornada=ElTemario.jornada3;
        }else{
            ElTemario.jornada="Selecciona una jornada de la lista.";
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaJornadaItemStateChanged

    private void ayudaTemarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaTemarioActionPerformed
        sonido();
         JOptionPane.showMessageDialog(null,ElTemario.explicacionTemario,
                    "Explicación Temario", JOptionPane.QUESTION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaTemarioActionPerformed

    private void ayudaRepasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaRepasoActionPerformed
        sonido();
         JOptionPane.showMessageDialog(null,ElRepaso.ayudaRepaso,
                    "Explicación Repaso", JOptionPane.QUESTION_MESSAGE);
// TODO add your handling code here:
    }//GEN-LAST:event_ayudaRepasoActionPerformed

    private void ListaJornada1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListaJornada1ItemStateChanged
        selecJornadaR= ListaJornada1.getSelectedItem();
        
       // TODO add your handling code here:
    }//GEN-LAST:event_ListaJornada1ItemStateChanged

    private void ListaJornada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaJornada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaJornada1ActionPerformed

    private void solucionRepasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solucionRepasoActionPerformed
            sonido();
            JOptionPane.showMessageDialog(null,ElRepaso.articuloJornada,
                    "Solución", JOptionPane.PLAIN_MESSAGE);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_solucionRepasoActionPerformed

    private void ayudaTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaTestActionPerformed
        sonido();
         JOptionPane.showMessageDialog(null,ElTest.explicacionTest,
                    "Explicación Teste", JOptionPane.QUESTION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaTestActionPerformed

    private void ayudaEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaEjerciciosActionPerformed
        sonido();
         JOptionPane.showMessageDialog(null,ElEjercicio.explicacionEjercicio,
                    "Explicación Ejercicio", JOptionPane.QUESTION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaEjerciciosActionPerformed

    private void ListaExamenesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListaExamenesItemStateChanged
        
        Object selecJornadaEjercicio= ListaExamenes.getSelectedItem();
        if(selecJornadaEjercicio.equals("2020")){
           ElEjercicio.examenEjercicio="examenPractico_2020.pdf";
        
        }else{
             ElEjercicio.examenEjercicio="sin_ejercicio.txt";
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaExamenesItemStateChanged

    private void ListaExamenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaExamenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaExamenesActionPerformed

    private void examenBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examenBotonActionPerformed
        File archivo = new File("src/ExamenesPracticos/"+examenEjercicio);
        try {
            Desktop.getDesktop().open(archivo);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_examenBotonActionPerformed

    private void ListaApartadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ListaApartadosItemStateChanged
       
        Object selecJornadaApartado= ListaApartados.getSelectedItem();
        if(selecJornadaApartado.equals("2020_ap_1")){
           ElEjercicio.examenApartado="ex2020apartado_1.txt";
        
        }else{
             ElEjercicio.examenApartado="sin_ejercicio.txt";
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ListaApartadosItemStateChanged

    private void ListaApartadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaApartadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaApartadosActionPerformed

    private void solucionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solucionBotonActionPerformed
        File archivo1 = new File("src/ExamenesPracticos/"+examenApartado);
        try {
            Desktop.getDesktop().open(archivo1);
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_solucionBotonActionPerformed

    private void listaTestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaTestItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listaTestItemStateChanged

    private void listaTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaTestActionPerformed

    private void testBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testBotonActionPerformed
        ExamenTest test= new ExamenTest();
        test.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_testBotonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ejercicios;
    private javax.swing.JButton Home;
    private javax.swing.JButton Labaraja;
    private javax.swing.JComboBox<String> ListaApartados;
    private javax.swing.JComboBox<String> ListaExamenes;
    private javax.swing.JComboBox<String> ListaJornada;
    private javax.swing.JComboBox<String> ListaJornada1;
    private javax.swing.JPanel PanelEjercicios;
    private javax.swing.JPanel PanelPortada;
    private javax.swing.JPanel PanelRepaso;
    private javax.swing.JPanel PanelTemario;
    private javax.swing.JPanel PanelTest;
    private javax.swing.JButton Repaso;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Temario;
    private javax.swing.JButton TemarioConstituc;
    private javax.swing.JButton TemarioDefensor;
    private javax.swing.JLabel TemarioEspecif;
    private javax.swing.JLabel TemarioEspecif1;
    private javax.swing.JLabel TemarioGeneral;
    private javax.swing.JLabel TemarioGeneral2;
    private javax.swing.JButton TemarioL39;
    private javax.swing.JButton TemarioL40;
    private javax.swing.JButton TemarioLGT;
    private javax.swing.JButton TemarioLGobierno;
    private javax.swing.JButton TemarioLIRPF;
    private javax.swing.JButton TemarioLIVA;
    private javax.swing.JButton TemarioLIgualdad;
    private javax.swing.JButton TemarioLJContencioso;
    private javax.swing.JButton TemarioLRBRLocal;
    private javax.swing.JButton TemarioLTransparencia;
    private javax.swing.JButton TemarioRDDepartamentos;
    private javax.swing.JButton TemarioRDDisciplinario;
    private javax.swing.JButton TemarioRGI;
    private javax.swing.JButton TemarioRGR;
    private javax.swing.JButton TemarioRGSAN;
    private javax.swing.JButton TemarioRIRPF;
    private javax.swing.JButton TemarioRIVA;
    private javax.swing.JButton TemarioRRVA;
    private javax.swing.JButton TemarioRTUE;
    private javax.swing.JButton TemarioTUE;
    private javax.swing.JButton TemarioTribunalC;
    private javax.swing.JButton Tests;
    private javax.swing.JLabel apartadoExamen;
    private javax.swing.JLabel autor;
    private javax.swing.JButton ayudaEjercicios;
    private javax.swing.JButton ayudaRepaso;
    private javax.swing.JButton ayudaTemario;
    private javax.swing.JButton ayudaTest;
    private javax.swing.JLabel bloc;
    private javax.swing.JPanel botones;
    private javax.swing.JButton calendario;
    private javax.swing.JLabel carpeta;
    private javax.swing.JLabel carta;
    private javax.swing.JLabel cuaderno;
    private javax.swing.JLabel cuaderno2;
    private javax.swing.JButton examenBoton;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fechaExamen;
    private javax.swing.JComboBox<String> listaTest;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel numeroCarta1;
    private javax.swing.JLabel numeroCarta2;
    private javax.swing.JLabel portada;
    private javax.swing.JButton solucionBoton;
    private javax.swing.JButton solucionRepaso;
    private javax.swing.JLabel tapete;
    private javax.swing.JButton testBoton;
    private javax.swing.JLabel textoExamen;
    private javax.swing.JLabel textoExamen1;
    private javax.swing.JLabel textoExamen2;
    private javax.swing.JLabel textoExamen3;
    private javax.swing.JLabel textoExamen4;
    private javax.swing.JLabel textoExamen5;
    private javax.swing.JLabel textoExamen6;
    private javax.swing.JLabel textoRepaso;
    private javax.swing.JLabel textoRepaso1;
    private javax.swing.JLabel textoRepaso2;
    private javax.swing.JLabel textoRepaso3;
    private javax.swing.JLabel textoRepaso4;
    private javax.swing.JLabel textoRepaso5;
    private javax.swing.JLabel tipoCarta;
    private javax.swing.JLabel tituloEjercicio;
    private javax.swing.JPanel ventana;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
